레이블 추가 기능 구현
codesquad-member-2020/issue-tracker-02 pull request #117
Opened 2020-06-20 16:27 UTC by delmaSong

### 구현 내용
레이블 추가 기능을 구현하였습니다.
 색상 랜덤 픽
  ColorPickerViewController에서 선택한 컬러 LabelPopUpViewController로 가져오기
  ColorPickerViewController의 초기화, 취소 버튼 제거
  ColorPickerViewController 뜰때마다 랜덤 컬러 선택되도록
  LabelPopUpViewController 첫 표시에도 랜덤컬러 지정되어있도록
  LabelPopUpViewController 뜰때마다 랜덤컬러 변경되도록
  제목 / 내용 / 컬러 값 가지고 LabelViewController로 이동
  레이블 추가 네트워크 요청
  갱신된 데이터로 라벨 목록 바인딩
  레이블 추가 버튼 다시 누르는 경우 모든 데이터 리셋
  색상 버튼 누르지 않고 submit 버튼 누르는 경우 기본 컬러 전달

2020-06-21 11:19 UTC, corykim0829 requested changes
수고하셨습니다!!!! 고민을 많이 한게 느껴지네요. 제 생각을 조금 적어보았습니다 ㅎ

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/PopUpViewController.swift
> +    func submitButtonDidTap(title: String, description: String?, additionalData: String?)
Label 객체를 인자로 넘겨주는 건 어떨까요? PopUpVC에서 추상화를 고려한다면 Encodable한 객체만 인자로 받는 것도 괜찮을 것 같은데 어떻게 생각하세요?

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Views/PopUpFooterView.swift
> +    func hideSecondaryButton() {
hideSupplementaryButtons는 어떨까요?

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/ColorPickerViewController.swift
> +                           blue: CGFloat.random(in: 0...1.0), alpha: 1),
extension으로 랜덤칼라를 generate하는 static 함수를 만들어도 좋을 것 같아요!

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/ColorPickerViewController.swift
> +                           blue: CGFloat.random(in: 0...1.0), alpha: 1),
displayP3Red 인자 앞에서 줄바꿈을 하면 좋을 것 같아요

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/ColorPickerViewController.swift
> +    private var selectedColorInfo: (color: UIColor, hexString: String)!
delegate로 넘겨주는건 알겠는데, hexString은 UIColor만 있으면 extension으로 만들 수 있으니 UIColor만 넘겨도 되지 않을까요?

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/ColorPickerViewController.swift
> +protocol ColorPickDelegate: class {
ColorPick을 대신하는게 아니라 ColorPickerVC에서 선택한 값을 전달만 하기 때문에 ColorPickerViewControllerDelegate가 적당하지 않을까요?

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/ColorPickerViewController.swift
> +    func pass(colorInfo: (color: UIColor, hexString: String))
결국에 이 동작은 SubmitButton을 눌러야 동작하기 때문에 SubmitButtonDidTap으로 명명해도 되지않을까요?

2020-06-21 11:19 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/Labels/Controllers/LabelPopUpViewController.swift
> +        configureRandomColor()
viewWillAppear와 configureUI 두번 호출되는데, configureUI는 언제 호출되나요?

2020-06-21 12:31 UTC, delmaSong commented on iOS/DoCollabo/DoCollabo/Labels/Controllers/LabelPopUpViewController.swift
> +        configureRandomColor()
`configureUI()` 는 맨 처음 `LabelPopUpViewController`가 생성되는 시점에 `configureLabelPopupViewController()` 메소드가 호출되면서 실행됩니다. `viewWillAppear()`에서 `configureUI()`가 아닌 `configureRandomColor()`를 호출하는 이유는 화면이 보여질때마다 `PopUpColorPickerView`를 생성해줄 필요가 없이 랜덤컬러만 변경해주면 되기때문에 그렇습니다

2020-06-21 12:37 UTC, delmaSong commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/PopUpViewController.swift
> +    func submitButtonDidTap(title: String, description: String?, additionalData: String?)
Encodable 한 타입을 인자로 받으면 전달되는건 인스턴스인데 그렇다면 PopUpViewController에서 Label 객체던 Milestone 객체던 구체적인 객체를 생성해야만 해서 적절하지 않은 것 같습니다. 필요한 데이터만 전달하고 LabelsViewController 혹은 LabelPopUpViewController 처럼 더 관계가 있는 곳에서 필요한 객체를 생성하는 것이 좋을 것 같다는 의견입니다.

2020-06-21 12:39 UTC, delmaSong commented
주신 의견 반영하여 수정 완료했습니다 🤝

2020-06-21 12:39 UTC, merged

2020-06-22 02:05 UTC, corykim0829 commented on iOS/DoCollabo/DoCollabo/PopUp/Controllers/PopUpViewController.swift
> +    func submitButtonDidTap(title: String, description: String?, additionalData: String?)
submitButtonDidTap 함수 인자에 들어가는게 조금 어색해서 그렇게 생각해봤습니다. additionalData가 String?타입인 것도 조금 어색하구요. notification처럼 userInfo 식의 Dictionary를 넘기는 것도 괜찮다는 생각이 드네요.